### ISSUE TITLE
failed to load Ressource

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/lottie#2]
Konnte es jetzt auch testen ... coole Sache das
In der Console erhalte ich folgenden Feher: 

failed to load Ressource: …`/assets/addons/lottie/vendor/lottie/lottie-player.js.map`

**Comment by danspringer** [comment]
Ah, die Safari-Map-Sache :-)

**Comment by skerbis** [comment]
ne du hast nicht die volle Distro dabei gepackt ... auch der chrome meckert es an

**Comment by skerbis** [comment]
Siehe PR
